site_name: "Markdown Exec"
site_description: "Utilities to execute code blocks in Markdown files."
site_url: "https://pawamoy.github.io/markdown-exec"
repo_url: "https://github.com/pawamoy/markdown-exec"
repo_name: "pawamoy/markdown-exec"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/markdown_exec]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage:
  - usage/index.md
  - Python: usage/python.md
  - Shell: usage/shell.md
  - Tree: usage/tree.md
- Gallery: gallery.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- attr_list
- callouts:
    strip_period: false
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
    base_path: [docs/snippets, "."]
- pymdownx.highlight
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
